# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.10.12                    # https://pyreadiness.org/3.10
  - pip=23.2.1                        # https://pip.pypa.io/en/stable/news
  - robocorp-truststore=0.8.0         # https://pypi.org/project/robocorp-truststore/
  - nodejs=16.20.2                    # https://github.com/nodejs/node/blob/main/CHANGELOG.md
  - pip:
    - robotframework-browser==17.5.2  # https://github.com/MarketSquare/robotframework-browser/releases
    - rpaframework==28.6.2            # https://rpaframework.org/releasenotes.html
    - webdriver-manager==4.0.2        # https://pypi.org/project/webdriver-manager/4.0.2/
    - robocorp==2.1.0             # https://pypi.org/project/robocorp
    - robocorp-browser==2.3.3     # https://pypi.org/project/robocorp-browser
    - robocorp-excel==0.4.4       # https://pypi.org/project/robocorp-excel
    - robocorp-http==0.4.1        # https://pypi.org/project/robocorp-http
    - requests==2.32.3            # https://pypi.org/project/requests/#history
